[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
flutter_rust_bridge = "2.9.0"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
unqlite = "1.5.0"
